### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by stinawest** [Dberg042/114-Gruppepresentasjon#13]

**Comment by Dberg042** [comment]
Vi kan bruke 
const parent = document.getElementById('parent');
const child = document.getElementById('child');
const btn = document.getElementById('btn');

btn.addEventListener('click',()=>{
  parent.appendChild(child);
})
appenchild method for homepage.

**Comment by Dberg042** [comment]
Modals works good, most of part of site is ready to use

**Comment by Dberg042** [comment]
Modals works without problem and we have tested in different platform.
