### ISSUE TITLE
Planlegging av koding

### ISSUE THREAD

**Issue by Anderstonheim** [Dberg042/114-Gruppepresentasjon#2]

**Comment by Dberg042** [comment]
Vi kan bruke _*appenchild*_ method i javascript to replace DOM element from aktiviterer til mine aktiviteter i hovedside.

https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_node_appendchild2

**Comment by stinawest** [comment]
![skisse nettside 104](https://user-images.githubusercontent.com/89196680/138279707-2b6a5323-368b-4789-a7c1-9364f5758161.jpg)

En skisse av hvordan nettsiden kan se ut

**Comment by stinawest** [comment]
Plan for koding
Målet med sidene vi lager til nettsiden er å virkeliggjøre scenario fra brukerreisen. Vi har med en innlogging fordi det er en del av brukerreisen. Brukeren får da opp en hjemmeside, hvor de ser kommende arrangementer, delt inn i tre kolonner. Den første kolonnen viser offentlige aktiviteter, den andre viser private aktiviteter, og den siste viser aktiviteter som brukeren har meldt seg på. I hver av kolonnene er det en beskrivelse av aktiviteten, med bilde og dato for informasjon. Der har man mulighet til å trykke «skal», som gjør at aktivitet-rubrikken flytter seg fra «offentlig/privat» til «mine arrangementer». På venstre side er det en hamburgermeny, hvor man kan gå inn til blant annet «hjem», «settings», «profil», «chat» og «gruppe». Disse skal ikke kodes, på grunn av at de er ekstra funksjoner til nettsiden, ikke prioritet for brukeren å nå målet sitt. 
Med en gang man har logget inn på siden, kan man se arrangementer. Med et enkelt klikk på en «join» knapp, kan brukeren melde seg på aktviteten.
