### ISSUE TITLE
Brukerreise

### ISSUE THREAD

**Issue by toreah** [Dberg042/114-Gruppepresentasjon#3]

**Comment by stinawest** [comment]
![brukerreise2](https://user-images.githubusercontent.com/89196680/140496643-d371acf6-2127-4477-9ebd-691433866acf.png)
![brukerreise 104](https://user-images.githubusercontent.com/89196680/140496646-c3d2a03b-165a-42f3-a78e-d31f321d99f8.png)

Skisser av brukerreise
