### ISSUE TITLE
ganttskjema

### ISSUE THREAD

**Issue by toreah** [Dberg042/114-Gruppepresentasjon#4]

**Comment by Anderstonheim** [comment]
[Ganttskjema 114.xlsx](https://github.com/toreah/114-Gruppepresentasjon/files/7372355/Ganttskjema.114.xlsx)

**Comment by stinawest** [comment]
![ganttskjema](https://user-images.githubusercontent.com/89196680/140496551-10b4f8aa-3b5e-4cd5-9a20-190e01221b35.png)
Ganttskjema (bilde)
