### ISSUE TITLE
refleksjon

### ISSUE THREAD

**Issue by Anderstonheim** [Dberg042/114-Gruppepresentasjon#9]

**Comment by stinawest** [comment]
Kort refleksjon: 
Samarbeid har fungert greit. Vi diskuterer sammen om hvordan vi skal gjøre ting, og så fordeler vi oppgaver. Prosjektet var i starten veldig forvirrende, det tok lang tid før vi visste hva vi skulle gjøre, og følte at andre grupper hadde oppfattet oppgaven på forskjellige måter. Vi tenker at hvis oppgaven var mer tydelig, så hadde prosessen gått raskere.

Av det vi lærte som var mest nyttig, var kanskje Google, Kanban-bord og bruk av Github. Vi har også fått prøvd ut gjennomføring av gruppearbeid i praksis.

Vi kunne ha lært mer om prosjektledelse. Kunna ha hatt flere undervisningtimer med koding (javascript) siden dette var nødvendig for å gjøre de to store prosjektene. Hadde vært fint å fått flere tilbakemedlinger underveis i prosjektet, slik at vi kunne lære mer av prosessen.
